Revert default ROOT_URL

diff --git a/meteorjs/s2i/bin/run b/meteorjs/s2i/bin/run
--- a/meteorjs/s2i/bin/run
+++ b/meteorjs/s2i/bin/run
@@ -12,8 +12,9 @@ run_meteor() {
     export PORT=${PORT:-8080}
 
     if [ -z "${ROOT_URL}" ]; then
-        export ROOT_URL="http://${GETUP_APP_NAME}-${GETUP_PROJECT_NAME}.getup.io:${PORT}/"
-        echo "No user supplied ROOT_URL. Using default ($ROOT_URL)"
+        echo "Missing environment variable ROOT_URL"
+        sleep 3
+        exit 1
     fi
 
     cd bundle
